[tool.mypy]
python_version = "3.10"
plugins = ["pydantic.mypy"]
ignore_missing_imports = true
exclude = '''(?x)(
      .git
    | __pycache__
    | .pytest_cache
)'''
warn_unreachable = true
warn_redundant_casts = true
strict_equality = true
disallow_any_unimported = true
enable_error_code = "redundant-expr, truthy-bool, unused-ignore"
explicit_package_bases = true


[tool.ruff]
exclude = [
    ".git",
    ".mypy_cache",
    "__pycache__",
    ".ruff_cache",
    ".venv",
    "venv",
]
# E501: We want to let Black manage too long lines
# UP007: Use X | Y for type annotations # we may want to use it but this would imply a lot of changes
ignore = ["E501", "UP007"]
# See https://beta.ruff.rs/docs/rules/ for available rules
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # Isort
    "UP",  # pyupgrade
    "S",   # flake8-bandit
    "DTZ", # flake8-datetimez # could be really usefull
    "T20", # flake8-print
    "PT",  # flake8-pytest-style # could be usefull for pytest
    "RET", # flake8-return
    "SIM", # flake8-simplify
]
# Same as Black.
line-length = 88
# Assume Python 3.10
target-version = "py310"


[tool.ruff.per-file-ignores]
# S101 Use of `assert` detected should not be enabled for tests directory
"tests/*" = ["S101"]
"app/tests/*" = ["S101"]


[tool.black]
line-length = 88
target-version = ['py310']
# "Black will automatically ignore files and directories in .gitignore file"
extend-exclude = '''
/(
    .git
)/
'''
